[workspace]
members = [
    "bin/reth",
    "crate-template",
    "crates/common/rlp",
    "crates/common/rlp-derive",
    "crates/consensus",
    "crates/executor",
    "crates/interfaces",
    "crates/net/common",
    "crates/net/ecies",
    "crates/net/eth-wire",
    "crates/net/discv4",
    "crates/net/dns",
    "crates/net/nat",
    "crates/net/network-api",
    "crates/net/network",
    "crates/net/test-utils",
    "crates/net/ipc",
    "crates/net/rpc",
    "crates/net/rpc-api",
    "crates/net/rpc-builder",
    "crates/net/rpc-types",
    "crates/net/downloaders",
    "crates/primitives",
    "crates/stages",
    "crates/storage/codecs",
    "crates/storage/db",
    "crates/storage/libmdbx-rs",
    "crates/storage/libmdbx-rs/mdbx-sys",
    "crates/storage/provider",
    "crates/tracing",
    "crates/tasks",
    "crates/tests",
    "crates/transaction-pool",
    "crates/metrics/metrics-derive",
    "crates/cli/utils",
]
default-members = ["bin/reth"]
