[package]
name = "reth-primitives"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Commonly used types in reth."

[dependencies]
# reth
reth-rlp = { path = "../common/rlp", features = [
    "std",
    "derive",
    "ethereum-types",
] }
reth-rlp-derive = { path = "../common/rlp-derive" }
reth-codecs = { version = "0.1.0", path = "../storage/codecs" }

revm-interpreter = { git = "https://github.com/bluealloy/revm", rev = "a05fb262d87c78ee52d400e6c0f4708d4c527f32", features = [
    "serde",
] }

# ethereum
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
parity-scale-codec = { version = "3.2.1", features = ["derive", "bytes"] }
tiny-keccak = { version = "2.0", features = ["keccak"] }

# Bloom
fixed-hash = { version = "0.8", default-features = false, features = [
    "rustc-hex",
] }

# crypto
secp256k1 = { version = "0.24.2", default-features = false, features = [
    "global-context",
    "alloc",
    "recovery",
] }

# used for forkid
crc = "1"

# misc
bytes = "1.2"
serde = "1.0"
serde_json = "1.0"
serde_with = "2.1.0"
thiserror = "1"
sucds = "0.5.0"
hex = "0.4"
hex-literal = "0.3"
modular-bitfield = "0.11.2"
derive_more = "0.99"
url = "2.3"
impl-serde = "0.4.0"
once_cell = "1.17.0"

# proof related
triehash = "0.8"
# See to replace hashers to simplify libraries
plain_hasher = "0.2"
hash-db = "0.15"

# arbitrary utils
arbitrary = { version = "1.1.7", features = ["derive"], optional = true }
proptest = { version = "1.0", optional = true }
proptest-derive = { version = "0.3", optional = true }
strum = { version = "0.24", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
hex-literal = "0.3"
test-fuzz = "3.0.4"
rand = "0.8"
revm-interpreter = { git = "https://github.com/bluealloy/revm", rev = "a05fb262d87c78ee52d400e6c0f4708d4c527f32", features = [
    "serde",
    "arbitrary",
] }

arbitrary = { version = "1.1.7", features = ["derive"] }
proptest = { version = "1.0" }
proptest-derive = "0.3"

# necessary so we don't hit a "undeclared 'std'": 
# https://github.com/paradigmxyz/reth/pull/177#discussion_r1021172198 
secp256k1 = "0.24.2"
criterion = "0.4.0"

[features]
default = []
arbitrary = [
    "revm-interpreter/arbitrary",
    "dep:arbitrary",
    "dep:proptest",
    "dep:proptest-derive",
]

[[bench]]
name = "recover_ecdsa_crit"
harness = false
